### ISSUE TITLE
export lifetime data

### ISSUE THREAD

**Issue by penguins125** [rado0x54/pysnoo#1]
So far snoo seems to only allow extraction of 24-hour chunks of data (or weekly averages)--can you allow it to export data over an arbitrary range (start and end DATETIME) and/or the lifetime?

**Comment by rado0x54** [comment]
Should be easy enough to do programmatically. Until this is implemented here, have a look at https://github.com/maebert/snoo

Please note, that the API only supports 24h session queries and that sessions can be torn apart by the 24h segments. To be really accurate, you'll have to join those split sessions back up again.
